server:
  port: 9999

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  #dao类和实体类的位置
  project: src/main/java
  #mapper文件的位置
  resources: src/main/resources

spring:
  datasource:
    # 数据库连接配置
    name: dingping
    url: jdbc:mysql://localhost:3306/dingping?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    # 数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  # add-mappings=true表示如果所有的controller都没有命中，则使用默认的静态资源处理器做匹配
  resources:
    add-mappings: true
  mvc:
    # 出现路径错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
    # 接入前端静态资源页面
    static-path-pattern: /static/**

  # #thymeleaf相关的配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

