server:
  port: 9999

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  #dao类和实体类的位置
  project: src/main/java
  #mapper文件的位置
  resources: src/main/resources

spring:
  datasource:
    # 数据库连接配置
    name: dingping
    url: jdbc:mysql://localhost:3306/dingping?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    # 数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

